spring:
    thymeleaf:
        prefix: classpath:templates/
        suffix: .html
        cache: false

    
    datasource:
        driver-class-name: org.mariadb.jdbc.Driver 
        url: jdbc:mariadb://localhost:3306/myboard?useUnicode=true&characterEncoding=utf-8 
        username: testUser
        password: 
    
    jpa:
        show-sql: true

        hibernate:
            ddl-auto: update
            format_sql: true
